name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:

    name: Setup Gcloud Account
    runs-on: ubuntu-latest
#    env:
#      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:

      - name: Login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gcr.io/todo-list-server-sample/todo-list-server-app-name .

      - name: Test Docker image
        run: docker run gcr.io/todo-list-server-sample/todo-list-server-app-name sh -c "cargo test"

      - name: Push Docker image
        run: docker push gcr.io/todo-list-server-sample/todo-list-server-app-name

      - name: Set project
        run: gcloud config set project todo-list-server-sample

      - name: Deploy Docker image
        run: gcloud run deploy todo-list-server-sample --image gcr.io/todo-list-server-sample/todo-list-server-app-name --region us-central1 --platform managed --allow-unauthenticated